# Generated by Django 2.0.3 on 2018-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortLinkId', models.CharField(max_length=200)),
                ('LongLinkValue', models.CharField(max_length=5000)),
                ('CreationDate', models.DateTimeField(verbose_name='Creation Date')),
                ('TTL', models.BigIntegerField(default=0)),
            ],
        ),
    ]
