# Generated by Django 2.0.5 on 2018-05-05 07:48

import ShortLinks.FieldModels.IntegerRangeField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortLinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='TTL',
            field=ShortLinks.FieldModels.IntegerRangeField.IntegerRangeField(default=0),
        ),
    ]
