# Generated by Django 2.0.5 on 2018-05-05 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ShortLinks', '0002_auto_20180505_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='TTL',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='ExpirationDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 8, 34, 18, 693207, tzinfo=utc), verbose_name='Expiration Date'),
        ),
    ]
