# Generated by Django 2.0.5 on 2018-05-21 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShortLinks', '0003_auto_20180505_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='TimesUsed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='ExpirationDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 21, 13, 13, 50, 862820, tzinfo=utc), verbose_name='Expiration Date'),
        ),
    ]
