# Generated by Django 2.0.5 on 2018-05-21 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShortLinks', '0005_auto_20180521_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='ExpirationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiration Date'),
        ),
    ]
