# Generated by Django 2.0.5 on 2018-05-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShortLinks', '0006_auto_20180521_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='CreatedBy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
